import type { Todo } from './types';

// Data mock untuk menampilkan daftar tugas
export const mockTodos: Todo[] = [
    {
        id: 1,
        title: 'Mempelajari React',
        description: 'Membaca dokumentasi terbaru dan contoh kode.',
        completed: true,
        category: 'Pribadi',
        priority: 'low',
    },
    {
        id: 2,
        title: 'Selesaikan tantangan koding',
        description: 'Membangun aplikasi to-do list full-stack untuk Industrix.',
        completed: false,
        category: 'Kerja',
        priority: 'high',
    },
    {
        id: 3,
        title: 'Belanja bahan makanan',
        description: 'Beli roti, susu, dan buah-buahan.',
        completed: false,
        category: 'Belanja',
        priority: 'medium',
    },
    {
        id: 4,
        title: 'Olahraga pagi',
        description: 'Lari 30 menit di taman.',
        completed: true,
        category: 'Pribadi',
        priority: 'low',
    },
    {
        id: 5,
        title: 'Menulis laporan mingguan',
        description: 'Ringkasan proyek dan kemajuan tim.',
        completed: false,
        category: 'Kerja',
        priority: 'high',
    },
    {
        id: 6,
        title: 'Membaca buku',
        description: 'Selesaikan bab 5 dari "The Alchemist".',
        completed: false,
        category: 'Pribadi',
        priority: 'medium',
    },
    {
        id: 7,
        title: 'Mengirim email ke klien',
        description: 'Tindak lanjuti proyek A.',
        completed: false,
        category: 'Kerja',
        priority: 'high',
    },
    {
        id: 8,
        title: 'Merencanakan liburan',
        description: 'Cari tempat tujuan dan tiket pesawat.',
        completed: false,
        category: 'Pribadi',
        priority: 'low',
    },
    {
        id: 9,
        title: 'Membuat presentasi',
        description: 'Buat slide untuk pertemuan tim.',
        completed: true,
        category: 'Kerja',
        priority: 'medium',
    },
    {
        id: 10,
        title: 'Mencuci mobil',
        description: 'Bersihkan mobil di akhir pekan.',
        completed: false,
        category: 'Pribadi',
        priority: 'low',
    },
];